config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  authenticated do
    root :to => 'organisations#index', as: :authenticated

    get 'users/show'
    get 'users/join_organisation'
    post 'users/join_organisation'
    patch 'users/join_organisation'
    delete 'users/leave_organisation'

    get 'update' => 'organisations#update', as: 'update'
  end

  resources :organisations do
    resources :shifts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :shifts, dependent: :destroy
  has_many :users, dependent: :nullify

  validates :name, uniqueness: { message: -> (object, data) do
      "#{data[:value]} is already taken! Please choose other name"
    end
  }
  validates :name, presence: true, length: { maximum: 30,
    too_long: "is above maximum length of %{count}" }
  validates :hourly_rate, presence: true
end

app/models/shift.rb
class Shift < ApplicationRecord
  has_one :user
  belongs_to :organisation
  
  validates :employee, presence: true
  validates :shift_start, presence: true
  validates :shift_end, presence: true
  validates :break_length, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :organisation
  has_many :shifts, dependent: :destroy
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      redirect_to organisations_path if user_signed_in?
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  
  def index
    already_org_member?
    @organisations = Organisation.all.order(created_at: :desc)
    @organisation = Organisation.new
  end

  def show
    @organisation = Organisation.find(params[:id])
    @org_shifts = @organisation.shifts.all.order(created_at: :desc)
  end

  def create
    @organisation = Organisation.create(org_params)

    if @organisation.save
      join_organisation
      redirect_to @organisation, notice: 'Organisation created successfully!'
    else
      render :index, notice: 'Oops something went wront.. Please try again!'
    end
  end

  def edit
    @organisation = Organisation.find(params[:id])
  end

  def update
    @organisation = Organisation.find(params[:id])
    if @organisation.update(org_params)
      redirect_to organisations_path, notice: "#{@organisation.name} updated successfully!"
    else
      render :edit, notice: 'Oops something went wront.. Please try again!'
    end
  end

  def destroy
    @organisation = Organisation.find(params[:id])
    @organisation.destroy
    redirect_to organisations_path, notice: 'Organisation successfully deleted!'
  end

  private

  def org_params
    params.require(:organisation).permit(:name, :hourly_rate)
  end

  def find_user
    @user = User.find_by(id: current_user.id)
  end

  def join_organisation
    @user.update(organisation_id: @organisation.id)
  end

  def already_org_member?
    if @user.organisation_id != nil
      redirect_to (organisations_path + "/#{@user.organisation_id}")
    end
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :authenticate_user!
  before_action :join_start_params, only: [:create]
  before_action :find_organisation
  before_action :find_shift, only: [:destroy, :edit]

  respond_to :html, :xml, :json

  def index
    @org_shifts = @organisation.shifts.all.order(created_at: :desc)
  end

  def create
    @shift = @organisation.shifts.create(shift_params)
    if @shift.save
      redirect_to @organisation, notice: 'Shift added!'
      # respond_with @organisation, notice: 'Shift added!'
    else
      redirect_to organisations_path(@organisation), notice: 'Oops something went wront.. Please try again!'
      # render :index, notice: 'Oops something went wront.. Please try again!'
    end
  end

  def update
    @shift = @organisation.shifts.find(params[:id])

    if @shift.update(shift_params)
      redirect_to @organisation, notice: 'Shift updated successfully!'
    else
      render :index, notice: 'Oops something went wront.. Please try again!'
    end
  end

  def destroy
    @shift.destroy
    redirect_to @organisation, notice: 'Shift deleted!'
  end

  private
  def shift_params
    params.require(:shift).permit(:employee, :shift_start, :shift_end, :break_length, :user_id)
  end

  def join_start_params
    if params[:shift].blank?
      return
    end
    shift_start_date = params[:shift].delete(:shift_start_date)
    shift_start_time = params[:shift].delete(:shift_start_time)
    shift_end_time = params[:shift].delete(:shift_end_time)
    # if shift_start_date.blank? || shift_start_time.blank?
    #   # TBC
    # else
    params[:shift][:shift_start] = Time.parse("#{shift_start_date} #{shift_start_time}")
    params[:shift][:shift_end] = Time.parse("#{shift_start_date} #{shift_end_time}")
    # end
  end

  def find_organisation
    @organisation = Organisation.find(params[:organisation_id])
  end

  def find_shift
    # @shift = @organisation.shifts.find(params[:id])
    @shift = Shift.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, :except[:index, :show]
  before_action :find_user

  def show
    @user
    is_org_member?
  end

  def join_organisation
    @organisation = Organisation.find(params[:org_id])
    @user.update(organisation_id: @organisation.id)
    redirect_to (organisations_path + "/#{@organisation.id}"), notice: 'Joined organisation!'
  end

  def leave_organisation
    org_name = find_left_organisation
    @user.update(organisation_id: nil)
    @user.shifts.destroy_all
    redirect_to organisations_path, notice: "Left #{org_name} and deleted shifts!"
  end

  private

  def find_user
    @user = User.find_by(id: current_user.id)
    redirect_to(root_url) unless @user == current_user
  end

  def find_left_organisation
    org = Organisation.find(@user.organisation_id)
    org.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/shifts_helper.rb
require 'time'

module ShiftsHelper
  def total_hours_worked(shift_start, shift_finish, break_min)
    finish_date = correct_finish_time(shift_start, shift_finish)

    min_worked = ((finish_date - shift_start) / 60) - break_min
    round_to_quarter(min_worked / 60)
  end
  
  def round_to_quarter(hours)
    (hours * 4).round / 4.0
  end

  private
  def correct_finish_time(date, time)
    Time.parse("#{date.strftime('%Y-%m-%d')} #{time.strftime('%H:%M')}")
  end
end

app/helpers/user_helper.rb
module UserHelper


  def is_org_member?
    @user.organisation_id != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class='index-box'>
  <div id='WFM'>
    <h4>WORKFIERCE MANAGEMENT</h4>
  </div>
  <div id='grow'>
    <h1>Grow your business</h1>
    <h1>and engage your teams</h1>
  </div>
  <div id='no-1'>
    <h3>The world’s #1 platform for rostering, attendance,</h3>
    <h3>labour insights and workforce success.</h3>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shift Space</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap"
      rel="stylesheet"
    />
    
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <section id='box'>
        <h1>shifts pace</h1>
        <%= render partial: "shared/flash" %>
      <%= yield %>
    </section>
  </body>
</html>

app/views/organisations/_edit.html.erb
<h2>Edit <%= @organisation.name %></h2><br>

<%= form_with(model: @organisation, remote: true, ) do |form| %>

  <% if @organisation.errors.any? %>
    <% @organisation.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
  <% end %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name, :class => 'center', required: true  %>
  </div>

  <div>
    <%= form.label 'Hourly rate £' %><br>
    <%= form.text_field :hourly_rate, :class => 'center', required: true  %>
  </div>
  <br>
  <div>
    <%= form.submit 'Update', :class => 'sml-edit' %>
  </div>
<% end %>

<%= button_to "Delete", organisation_path(@organisation),
            :class => 'sml-join',
            method: :delete,
            data: { confirm: "Are you sure?" } %> 

app/views/organisations/_helper-functions.html.erb
<script>
  function displayShifts() {
    const x = document.getElementById("hidden-shifts-field");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }

  function displayAddShifts() {
    const x = document.getElementById("hidden-add-field");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }

  function displayEditShifts() {
    const x = document.getElementById("hidden-edit-field");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }

    function displayAddOrg() {
    const x = document.getElementById("hidden-add-org");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

app/views/organisations/_new.html.erb
<div class='edit-box'>
  <%= form_with(model: @organisation, remote: true, ) do |form| %>

    <% if @organisation.errors.any? %>
    <div id='notice' >
      <% @organisation.errors.full_messages.each do |msg| %>
        <%= msg %>
      <% end %>
    </div>
    <% end %>

    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name, id: "name", :class => 'center', required: true  %>
    </div>

    <div>
      <%= form.label 'Hourly rate £' %><br>
      <%= form.text_field :hourly_rate, id: "hourly_rate", :class => 'center', required: true  %>
    </div>
    <div>
      <%= form.submit 'Join', :id => 'create-join', :class => 'sml-button' %>
    </div>
  <% end %>
</div>

app/views/organisations/edit.html.erb
<h2>Edit <%= @organisation.name %></h2>

<%= render partial: "form" %> 

<%= link_to "Delete", organisation_path(@organisation),
            method: :delete,
            data: { confirm: "Are you sure?" } %> 

app/views/organisations/edit.js.erb
$('#edit-org a').parent().html('<%= j render :partial => 'organisations/edit', organisation: @organisation, :formats => :html %>');
$('#edit-org-<%=params[:id]%>').parent().html('<%= j render :partial => 'organisations/edit', :formats => :html %>');

app/views/organisations/index.html.erb
<section class='org-index'>
  <h2>Organisations</h2>
  <br>
  <% if !is_org_member? %>
    <p>You aren't a member of any organisation yet</p>
    <p>Join an existing organisation or create a new one</p>
  <% end %>

  <%= render partial: "organisations/helper-functions" %>
  <button class='sml-button' onclick="displayAddOrg()">Create new Organisation</button>
  <div id="hidden-add-org" style='display:none'>
      <%= render partial: "new" %> 
  </div>

  <ul>
    <% @organisations.each do |org| %>
      <div class='each-org'>

        <%= org.name %>

        <br><% org_id = org.id %><br>
        <div id='flex'>
          <%= button_to "Join", users_join_organisation_path(@user, org_id: org_id),
                                method: :post, :class => 'sml-join', :id => 'join', remote: true %>

          <div id=<%= "edit-org-#{org.id}" %> >
            <%= button_to "Edit", edit_organisation_path(@organisation, id: org_id), 
                                  method: :get, :class => 'sml-edit', remote: true  %>
          </div>
        </div>
      </div>
    <% end %>
  </ul>
</section>

app/views/organisations/new.js.erb
$('#new-org a%>').parent().html('<%= j render :partial => 'organisations/new', :formats => :html %>');

app/views/organisations/show-2.html.erb
<h2><%= @organisation.name %></h2>

<%= render partial: "organisations/helper-functions" %>

<button onclick="displayAddShifts()">Add Shift</button>
<button onclick="displayShifts()">View Shifts</button>
<button onclick="displayEditShifts()">Edit <%= @organisation.name %></button>

<div id="hidden-add-field" style='display:none'>
  <%= render partial: "shifts/new" %>
</div>

<div id="hidden-edit-field" style='display:none'>
  <%= render partial: "organisations/edit" %>
</div>

<div id="hidden-shifts-field" style='display:none'>
  <%= render partial: "shifts/shifts" %>
</div>

<div id='leave-organisation' style='display:none'>
  <%= link_to "Leave", users_leave_organisation_path,
                       method: :delete,
                       remote: true,
                       data: { confirm: "Are you sure?" } %>
</div>

app/views/organisations/show.html.erb
<section class='show-org'> 
  <div class='fieldd-shifts'>
    <h2 class='center'><%= @organisation.name %></h2>
    <br>
    <div id='view-shifts'>
      <%= button_to "View Shifts", organisation_shifts_path(@organisation), 
                                   :class => 'sml-button', method: :get, remote: true %>
    </div>
    <br>
  </div>
  
  <section class='details'>
    <section id='details-box'>
      <div id="add-shift" class='add-div'>
        <%= link_to "Add Shift", new_organisation_shift_path(@organisation), :id => 'center', :class => 'sml-link', remote: true %>
      </div>
    </section>
    <section id='bio-box'>
      <div id="edit-org" class='add-div'>
        <%= link_to "Edit", edit_organisation_path(@organisation), :class => 'sml-link', method: :get, remote: true  %>
      </div>
    </section>
  </section>

  <section class='feed-box'>

    <div id='leave-organisation'>
      <%= button_to "Leave", users_leave_organisation_path,
                         method: :delete,
                         :class => 'sml-leave',
                         remote: true,
                         data: { confirm: "Are you sure?" } %>
    </div>
  </section>

</section>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div id='notice'>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div id='notice'>
    <%= flash[:alert] %>
  </div>
<% end %>

<% if flash[:success] %>
  <div id='notice'>
    <%= flash[:success] %>
  </div>
<% end %>

<%# <% if @organisation.errors.any? %> 
  <%# <div id='notice' > %>
    <%# <% @organisation.errors.full_messages.each do |msg| %> 
      <%# <%= msg %> 
    <%# <% end %> 
  <%# </div> %>
<%# <% end %> 

app/views/shared/_navbar.html.erb
<nav class='bar-box'>
  <div class='some-collapse-navbar'>
    <li class='logo-li'>
      <% if user_signed_in? %>
        <%# <% user_org_id = current_user.organisation_id %>
        <%= link_to image_tag('lonely-boy.gif', :class => 'logo'),
            (organisations_path + "/#{current_user.organisation_id}") %>
      <% else %>
        <%= link_to image_tag('lonely-boy.gif', :class => 'logo'), root_path %>
      <% end %>
    </li>
    <% if user_signed_in? %>
      <li class='li-box'>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, :id => 'log-out' %>
      </li>
        <% if current_user.organisation_id != nil %>
          <li class='li-box'>
            <%= link_to "Leave", users_leave_organisation_path,
                         method: :delete,
                         remote: true,
                         data: { confirm: "Are you sure?" } %>
          </li>
        <% end %>
        <p id='vp'>Logged in as <%= current_user.name %></p>
    <% else %>
      <li class='li-box'>
        <%= link_to "Log In", new_user_session_path %>
      </li>
      <li class='li-box'>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
    <% end %>
  </div>
</nav>

app/views/shifts/_form.html.erb
<%= form_with model: [ @organisation, @organisation.shifts.build ] do |form| %>
  <tr>
    <td><%= current_user.name %></td>
    <td><%= form.date_field :shift_start_date, required: true %></td>
    <td><%= form.time_field :shift_start_time, required: true %></td>
    <td><%= form.time_field :shift_end_time, required: true %></td>
    <td><%= form.text_field :break_length, required: true %></td>
    <%= form.hidden_field :employee, value: current_user.name %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <td><%= form.submit %></td>
  </tr>
<% end %>

app/views/shifts/_index.html.erb
<% if @organisation.shifts.empty? %>

  <p id='center'><%= @organisation.name %> has no shifts yet! Add a new one</p>

<% else %>

  <div id='shifts-table'>
    <h3>Shifts</h3>
    <table>
      <thead>
        <tr>
          <th>Employee Name</td>
          <th>Shift date</td>
          <th>Start time</td>
          <th>Finish time</td>
          <th>Break length (min)</td>
          <th>Hours worked</td>
          <th>Shift cost</td>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "shifts/show" %>
        <%# <%= render partial: "shifts/new" %>
      </tbody>
    </table>
  </div>

<% end %>

app/views/shifts/_new.html.erb
<div id='add-shift'>
  <%= form_with model: [ @organisation, @organisation.shifts.build ] do |form| %>
    <a>New Shift for <%= current_user.name %></a><br><br>
    <a>shift date: <%= form.date_field :shift_start_date, :class => 'sml-button', required: true %></a>
    <a>start time: <%= form.time_field :shift_start_time, :class => 'sml-button', required: true %></a>
    <a>finish time: <%= form.time_field :shift_end_time, :class => 'sml-button', required: true %></a>
    <a>break length:</a><br> <%= form.text_field :break_length, :class => 'sml-text', :style => 'width:50px;height:5vh', required: true %></a><br>
    <%= form.hidden_field :employee, value: current_user.name %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <br>
    <%= form.submit 'Create', :class => 'sml-button' %>
  <% end %>
</div>

app/views/shifts/_show.html.erb
<% @org_shifts.each do |shift| %>
  <tr>
    <td><%= shift.employee %></td> 
    <td><%= shift.shift_start.strftime('%m/%d/%Y')%></td>
    <td><%= shift.shift_start.strftime('%H:%M%P')%></td>
    <td><%= shift.shift_end.strftime('%H:%M%P') %></td>
    <% hours_worked = total_hours_worked(
                               shift.shift_start, 
                               shift.shift_end,
                               shift.break_length)%>
    <td><%= shift.break_length %></td>
    <td><%= hours_worked %></td>
    <td>£ <%= '%.2f' % round_to_quarter(@organisation.hourly_rate * hours_worked) %></td>
    <% if current_user.id == shift.user_id %>
      <td>
        <%= link_to "Edit", edit_organisation_shift_path(@organisation, shift) %>
        <%= link_to "Delete", [@organisation, shift],
          method: :delete,
          data: { confirm: "Are you sure?" } %>
      </td>
    <% end %>
  </tr>
<% end %>

app/views/shifts/edit.html.erb
<section class='login-box'>
  <div id='add-shift' class='center'>
    <h2>Edit <%= @shift.employee %>'s shift</h2>
  
    <%= form_with model: [ @organisation, @shift ] do |form| %>
  
        <a>employee:<%= current_user.name %></a><br><br>
        <a>shift date: <%= form.date_field :shift_start, :class => 'sml-button' %></a>
        <a>start time: <%= form.time_field :shift_start, :class => 'sml-button' %></a>
        <a>finish time: <%= form.time_field :shift_end, :class => 'sml-button' %></a>
        <a>break length:</a><br><%= form.text_field :break_length, :class => 'sml-text', :style => 'width:50px;height:5vh' %>
        <%= form.hidden_field :employee, value: current_user.name %>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <br><br>
        <td><%= form.submit 'Update', :class => 'sml-button' %>
  
    <% end %>
  </div>
</section>

app/views/shifts/index.html.erb
<h2><%= @organisation.name %></h2>

<%= link_to "Back", organisation_path(@organisation) %>

<h3>Shifts</h3>
<table>
  <thead>
    <tr>
      <th>Employee Name</td>
      <th>Shift date</td>
      <th>Start time</td>
      <th>Finish time</td>
      <th>Break length (min)</td>
      <th>Hours worked</td>
      <th>Shift cost</td>
      <%# <th>Update</td %>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "shifts/show" %> 
    <%= render partial: "shifts/form" %> 
  </tbody>
</table>

app/views/shifts/index.js.erb
$('#view-shifts').html('<%= j render :partial => 'shifts/index', :formats => :html %>');

app/views/shifts/new.js.erb
$('#add-shift a').parent().html('<%= j render :partial => 'shifts/new', :formats => :html %>');

app/views/users/show.html.erb
<%= @user.name %>

<%= link_to "Delete my Shifts", users_leave_organisation_path,
            method: :delete,
            data: { confirm: "Are you sure?" } %>